fix: exclude tinyexec from build bundle (#639)
Gives an error, might be a bug in the bundler of Bun

```
file:///Users/janbevers/Projects/sdk/sdk/cli/dist/cli.js:273253
import { spawn as de } from "child_process";
                  ^^

SyntaxError: Identifier 'de' has already been declared
    at compileSourceTextModule (node:internal/modules/esm/utils:338:16)
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:102:18)
    at #translate (node:internal/modules/esm/loader:437:12)
    at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:484:27)
    at async ModuleJob._link (node:internal/modules/esm/module_job:115:19)
```