chore(deps): update dependency commander to v14 (#1017)
This PR contains the following updates:

| Package | Type | Update | Change | OpenSSF |
|---|---|---|---|---|
| [commander](https://redirect.github.com/tj/commander.js) |
dependencies | major | [`11.1.0` ->
`14.0.0`](https://renovatebot.com/diffs/npm/commander/11.1.0/14.0.0) |
[![OpenSSF
Scorecard](https://api.securityscorecards.dev/projects/github.com/tj/commander.js/badge)](https://securityscorecards.dev/viewer/?uri=github.com/tj/commander.js)
|
| [commander](https://redirect.github.com/tj/commander.js) |
devDependencies | major | [`11.1.0` ->
`14.0.0`](https://renovatebot.com/diffs/npm/commander/11.1.0/14.0.0) |
[![OpenSSF
Scorecard](https://api.securityscorecards.dev/projects/github.com/tj/commander.js/badge)](https://securityscorecards.dev/viewer/?uri=github.com/tj/commander.js)
|

---

### Release Notes

<details>
<summary>tj/commander.js (commander)</summary>

###
[`v14.0.0`](https://redirect.github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1400-2025-05-18)

[Compare
Source](https://redirect.github.com/tj/commander.js/compare/v13.1.0...v14.0.0)

##### Added

- support for groups of options and commands in the help using low-level
`.helpGroup()` on `Option` and `Command`, and higher-level
`.optionsGroup()` and `.commandsGroup()` which can be used in chaining
way to specify group title for following options/commands
(\[[#&#8203;2328](https://redirect.github.com/tj/commander.js/issues/2328)])
- support for unescaped negative numbers as option-arguments and
command-arguments
(\[[#&#8203;2339](https://redirect.github.com/tj/commander.js/issues/2339)])
- TypeScript: add `parseArg` property to `Argument` class
(\[[#&#8203;2359](https://redirect.github.com/tj/commander.js/issues/2359)])

##### Fixed

- remove bogus leading space in help when option has default value but
not a description
(\[[#&#8203;2348](https://redirect.github.com/tj/commander.js/issues/2348)])
- `.configureOutput()` now makes copy of settings instead of modifying
in-place, fixing side-effects
(\[[#&#8203;2350](https://redirect.github.com/tj/commander.js/issues/2350)])

##### Changed

-   *Breaking:* Commander 14 requires Node.js v20 or higher
- internal refactor of `Help` class adding `.formatItemList()` and
`.groupItems()` methods
(\[[#&#8203;2328](https://redirect.github.com/tj/commander.js/issues/2328)])

###
[`v13.1.0`](https://redirect.github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1310-2025-01-21)

[Compare
Source](https://redirect.github.com/tj/commander.js/compare/v13.0.0...v13.1.0)

##### Added

- support a pair of long option flags to allow a memorable shortened
flag, like `.option('--ws, --workspace')`
(\[[#&#8203;2312](https://redirect.github.com/tj/commander.js/issues/2312)])

###
[`v13.0.0`](https://redirect.github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1300-2024-12-30)

[Compare
Source](https://redirect.github.com/tj/commander.js/compare/v12.1.0...v13.0.0)

##### Added

- support multiple calls to `.parse()` with default settings
(\[[#&#8203;2299](https://redirect.github.com/tj/commander.js/issues/2299)])
- add `.saveStateBeforeParse()` and `.restoreStateBeforeParse()` for use
by subclasses
(\[[#&#8203;2299](https://redirect.github.com/tj/commander.js/issues/2299)])
- style routines like `styleTitle()` to add color to help using
`.configureHelp()` or Help subclass
(\[[#&#8203;2251](https://redirect.github.com/tj/commander.js/issues/2251)])
- color related support in `.configureOutput()` for `getOutHasColors()`,
`getErrHasColors()`, and `stripColor()`
(\[[#&#8203;2251](https://redirect.github.com/tj/commander.js/issues/2251)])
- Help property for `minWidthToWrap`
(\[[#&#8203;2251](https://redirect.github.com/tj/commander.js/issues/2251)])
- Help methods for `displayWidth()`, `boxWrap()`, `preformatted()` et al
(\[[#&#8203;2251](https://redirect.github.com/tj/commander.js/issues/2251)])

##### Changed

- *Breaking*: excess command-arguments cause an error by default, see
migration tips
(\[[#&#8203;2223](https://redirect.github.com/tj/commander.js/issues/2223)])
- *Breaking*: throw during Option construction for unsupported option
flags, like multiple characters after single `-`
(\[[#&#8203;2270](https://redirect.github.com/tj/commander.js/issues/2270)])
    -   note: support for dual long option flags added in Commander 13.1
- *Breaking*: throw on multiple calls to `.parse()` if
`storeOptionsAsProperties: true`
(\[[#&#8203;2299](https://redirect.github.com/tj/commander.js/issues/2299)])
- TypeScript: include implicit `this` in parameters for action handler
callback
(\[[#&#8203;2197](https://redirect.github.com/tj/commander.js/issues/2197)])

##### Deleted

- *Breaking*: `Help.wrap()` refactored into `formatItem()` and
`boxWrap()`
(\[[#&#8203;2251](https://redirect.github.com/tj/commander.js/issues/2251)])

##### Migration Tips

**Excess command-arguments**

It is now an error for the user to specify more command-arguments than
are expected. (`allowExcessArguments` is now false by default.)

Old code:

```js
program.option('-p, --port <number>', 'port number');
program.action((options) => {
  console.log(program.args);
});
```

Now shows an error:

```console
$ node example.js a b c
error: too many arguments. Expected 0 arguments but got 3.
```

You can declare the expected arguments. The help will then be more
accurate too. Note that declaring
new arguments will change what is passed to the action handler.

```js
program.option('-p, --port <number>', 'port number');
program.argument('[args...]', 'remote command and arguments'); // expecting zero or more arguments
program.action((args, options) => {
  console.log(args);
});
```

Or you could suppress the error, useful for minimising changes in legacy
code.

```js
program.option('-p, --port', 'port number');
program.allowExcessArguments();
program.action((options) => {
  console.log(program.args);
});
```

**Stricter option flag parsing**

Commander now throws an error for option flag combinations that are not
supported.
In particular, a short flag with multiple characters is now an error.

```js
program.option('-ws, --workspace'); // throws error
```

A short option has a single character:

```js
program.option('-w, --workspace');
```

Or from Commander 13.1 you can have an extra long flag instead of a
short flag to allow a more memorable shortcut for the full name:

```js
program.option('--ws, --workspace');
```

###
[`v12.1.0`](https://redirect.github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1210-2024-05-18)

[Compare
Source](https://redirect.github.com/tj/commander.js/compare/v12.0.0...v12.1.0)

##### Added

- auto-detect special node flags `node --eval` and `node --print` when
call `.parse()` with no arguments
(\[[#&#8203;2164](https://redirect.github.com/tj/commander.js/issues/2164)])

##### Changed

- prefix require of Node.js core modules with `node:`
(\[[#&#8203;2170](https://redirect.github.com/tj/commander.js/issues/2170)])
- format source files with Prettier
(\[[#&#8203;2180](https://redirect.github.com/tj/commander.js/issues/2180)])
- switch from StandardJS to directly calling ESLint for linting
(\[[#&#8203;2153](https://redirect.github.com/tj/commander.js/issues/2153)])
- extend security support for previous major version of Commander
(\[[#&#8203;2150](https://redirect.github.com/tj/commander.js/issues/2150)])

##### Removed

- removed unimplemented Option.fullDescription from TypeScript
definition
(\[[#&#8203;2191](https://redirect.github.com/tj/commander.js/issues/2191)])

###
[`v12.0.0`](https://redirect.github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1200-2024-02-03)

[Compare
Source](https://redirect.github.com/tj/commander.js/compare/v11.1.0...v12.0.0)

##### Added

- `.addHelpOption()` as another way of configuring built-in help option
(\[[#&#8203;2006](https://redirect.github.com/tj/commander.js/issues/2006)])
- `.helpCommand()` for configuring built-in help command
(\[[#&#8203;2087](https://redirect.github.com/tj/commander.js/issues/2087)])

##### Fixed

- *Breaking:* use non-zero exit code when spawned executable subcommand
terminates due to a signal
(\[[#&#8203;2023](https://redirect.github.com/tj/commander.js/issues/2023)])
- *Breaking:* check `passThroughOptions` constraints when using
`.addCommand` and throw if parent command does not have
`.enablePositionalOptions()` enabled
(\[[#&#8203;1937](https://redirect.github.com/tj/commander.js/issues/1937)])

##### Changed

- *Breaking:* Commander 12 requires Node.js v18 or higher
(\[[#&#8203;2027](https://redirect.github.com/tj/commander.js/issues/2027)])
- *Breaking:* throw an error if add an option with a flag which is
already in use
(\[[#&#8203;2055](https://redirect.github.com/tj/commander.js/issues/2055)])
- *Breaking:* throw an error if add a command with name or alias which
is already in use
(\[[#&#8203;2059](https://redirect.github.com/tj/commander.js/issues/2059)])
- *Breaking:* throw error when calling `.storeOptionsAsProperties()`
after setting an option value
(\[[#&#8203;1928](https://redirect.github.com/tj/commander.js/issues/1928)])
- replace non-standard JSDoc of `@api private` with documented
`@private`
(\[[#&#8203;1949](https://redirect.github.com/tj/commander.js/issues/1949)])
- `.addHelpCommand()` now takes a Command (passing string or boolean
still works as before but deprecated)
(\[[#&#8203;2087](https://redirect.github.com/tj/commander.js/issues/2087)])
- refactor internal implementation of built-in help option
(\[[#&#8203;2006](https://redirect.github.com/tj/commander.js/issues/2006)])
- refactor internal implementation of built-in help command
(\[[#&#8203;2087](https://redirect.github.com/tj/commander.js/issues/2087)])

##### Deprecated

- `.addHelpCommand()` passing string or boolean (use `.helpCommand()` or
pass a Command)
(\[[#&#8203;2087](https://redirect.github.com/tj/commander.js/issues/2087)])

##### Removed

- *Breaking:* removed default export of a global Command instance from
CommonJS (use the named `program` export instead)
(\[[#&#8203;2017](https://redirect.github.com/tj/commander.js/issues/2017)])

##### Migration Tips

**global program**

If you are using the
[deprecated](./docs/deprecated.md#default-import-of-global-command-object)
default import of the global Command object, you need to switch to using
a named import (or create a new `Command`).

```js
// const program = require('commander');
const { program } = require('commander');
```

**option and command clashes**

A couple of configuration problems now throw an error, which will pick
up issues in existing programs:

-   adding an option which uses the same flag as a previous option
- adding a command which uses the same name or alias as a previous
command

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At 12:00 AM through 04:59 AM and 10:00
PM through 11:59 PM, Monday through Friday ( * 0-4,22-23 * * 1-5 ), Only
on Sunday and Saturday ( * * * * 0,6 ) (UTC), Automerge - At any time
(no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [x] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/settlemint/sdk).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MC4xMS4xOCIsInVwZGF0ZWRJblZlciI6IjQwLjExLjE4IiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6WyJkZXBlbmRlbmNpZXMiXX0=-->

Signed-off-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>